### ISSUE TITLE
Can't update Event Restriction on clear.codeday.org

### ISSUE THREAD

**Issue by yednapg** [codeday/www-clear#35]
<img width="1792" alt="Screenshot 2023-04-09 at 10 30 34 PM" src="https://user-images.githubusercontent.com/103869798/230786148-5b9145f1-ce7f-4916-8aad-4aa922e9a675.png">

**Comment by tylermenezes** [comment]
This is correct, event restrictions are now managed globally (so that they can be translated). I can invite you to Contentful where you can manage a lot of shared stuff like this; DM me your CodeDay email.

**Comment by tylermenezes** [comment]
(The link should be removed though!)

**Comment by yednapg** [comment]
Thanks, Tyler!

I am already on Contentful. However, I don't know why, but I am able to change the event restrictions in Singapore. Maybe it's a bug. 

<img width="847" alt="Screenshot 2023-04-10 at 9 37 48 PM" src="https://user-images.githubusercontent.com/103869798/230943016-aff3d917-62e3-4213-a43f-27e21ab329d8.png">
